# analysis_options.yaml

# 基础规则：继承 flutter_lints 的默认推荐
include: package:flutter_lints/flutter.yaml

analyzer:
  # 排除无需分析的文件
  exclude:
#    - "**/*.g.dart"      # 忽略生成的代码（如 JSON 序列化）
    - "build/**"         # 构建产物目录
    - "ios/**"           # iOS 原生代码
    - "android/**"       # Android 原生代码

  # 强类型模式（提升代码安全性）
  strong-mode:
    implicit-casts: false   # 禁止隐式类型转换
    implicit-dynamic: false # 禁止隐式 dynamic

  # 关键错误规则（必须修复）
  errors:
    avoid_print: error         # 禁止直接使用 print
#    unused_import: error       # 禁止未使用的导入
    missing_required_param: error  # 必须参数缺失

linter:
  rules:
    # Flutter 核心规范
    use_key_in_widget_constructors: true  # Widget 必须带 key
    use_build_context_synchronously: true # 安全使用 BuildContext

    # 基础代码质量
    prefer_const_constructors: true       # 推荐使用 const 构造函数
    prefer_final_locals: true             # 局部变量尽量用 final
    avoid_unnecessary_containers: true    # 避免冗余的 Container